[workspace]
members = ["crates/zee-core", "crates/zee-tui", "crates/zee-gui", "plugins/zee-plugin-text"]
resolver = "2"

[workspace.dependencies]
anyhow        = { version = "1.0", features = ["backtrace"] }
serde         = { version = "1.0", features = ["derive"] }
toml-span     = "0.6"
regex         = "1.12"
aho-corasick  = "1.1"
unicode-width = "0.2"
encoding_rs   = "0.8"
ropey         = "1.6"
rayon         = "1.11"
chrono        = "0.4"
humantime     = "2.1"
serde_json    = "1.0"
wasmi         = "0.40"
unicode-linebreak = "0.1.5"
