[meta]
name = "CSS"
extensions = ["css"]

[[rule]]
token = "keyword"
pattern = "[a-zA-Z-]+\\s*:"

[[rule]]
token = "string"
pattern = "\".*?\"|'.*?'"

[[rule]]
token = "type_name"
pattern = "\\.[a-zA-Z0-9_-]+"

[[rule]]
token = "type_name"
pattern = "#[a-zA-Z0-9_-]+"

[[rule]]
token = "attribute"
pattern = "@[a-zA-Z-]+"

[[rule]]
token = "comment"
start = "/\\*"
end = "\\*/"

[[rule]]
token = "constant"
pattern = "![a-zA-Z]+"
