[package]
name = "zee-core"
version = "0.1.18"
edition = "2021"


[dependencies]
anyhow        = { workspace = true }
serde         = { workspace = true }
toml          = "0.8"
toml-span     = { workspace = true }
regex         = { workspace = true }
aho-corasick  = { workspace = true }
unicode-width = { workspace = true }
unicode-linebreak = { workspace = true }
encoding_rs   = { workspace = true }
ropey         = { workspace = true }
rayon         = { workspace = true }
serde_json    = { workspace = true }
wasmi         = { workspace = true }
wasmtime      = { workspace = true }
ureq          = { version = "2.10", features = ["json"] }
flate2        = "1.0"
tar           = "0.4"
zip           = { version = "2.2", default-features = false, features = ["deflate"] }
mlua          = { version = "0.9", features = ["lua54", "vendored"] }

[target.'cfg(unix)'.dependencies]
libc          = "0.2"

[dev-dependencies]
wat = "1.261"
