[package]
name = "zee-tui"
version = "0.1.8"
edition = "2021"

[[bin]]
name = "zee"
path = "src/main.rs"

[dependencies]
zee-core  = { path = "../zee-core" }
crossterm = "0.28"
anyhow    = { workspace = true }
base64    = "0.22"
unicode-width = { workspace = true }
chrono    = { workspace = true }
humantime = { workspace = true }
arboard = "3.6.1"
