[package]
name = "zee-tui"
version = "0.2.5"
edition = "2021"


[lib]
name = "zee_tui"
path = "src/lib.rs"

[[bin]]
name = "zee"
path = "src/main.rs"

[[bin]]
name = "zee-cli"
path = "src/bin/zee_cli.rs"

[dependencies]
zee-core  = { path = "../zee-core" }
crossterm = "0.28"
anyhow    = { workspace = true }
base64    = "0.22"
unicode-width = { workspace = true }
chrono    = { workspace = true }
humantime = { workspace = true }
arboard = "3.6.1"
